const x = {
  line_items: [
    {
      label: 'Salted Cashews',
      name: 'Salted Cashews',
      value: 0,
      catalog_object_id: 'ZKQKIGZP5FZBS3QJRRISLITW',
      src: '/static/media/salted_ml_nuts_front.5a9aab3d1c8cb07b6e24.png',
      alt: 'salted',
      item_type: 'ITEM',
      price: 40,
      stock: 56,
      details: [
        'Roasted & Salted',
        'Buttery in texture',
        'Mild in flavor',
        'Sealed for freshness',
        'Grown & Harvested in Oklahoma',
        '100% recyclable',
        'NET WT 8oz',
      ],
      desc: {
        type: 'span',
        key: null,
        ref: null,
        props: {
          children: [
            "These aren't just a delicious treat; they're an ode to",
            ' ',
            {
              type: 'span',
              key: null,
              ref: null,
              props: {
                className: '!font-[500]',
                children: "America's favorite nut",
              },
              _owner: null,
              _store: {},
            },
            '. Whether you wish to collect memorabilia to commemorate',
            ' ',
            {
              type: 'span',
              key: null,
              ref: null,
              props: { className: '!font-[500]', children: '45' },
              _owner: null,
              _store: {},
            },
            ", or express that you've exhausted just about every mental faculty trying to figure out what",
            ' ',
            {
              type: 'i',
              key: null,
              ref: null,
              props: { children: '"non-binary"' },
              _owner: null,
              _store: {},
            },
            ' means. One things for certain, another four years of',
            ' ',
            {
              type: 'i',
              key: null,
              ref: null,
              props: { children: 'Sleepy Joe & Co.' },
              _owner: null,
              _store: {},
            },
            " and we won't be able to identify as",
            ' ',
            {
              type: 'span',
              key: null,
              ref: null,
              props: { className: '!font-[500]', children: 'America' },
              _owner: null,
              _store: {},
            },
            '. This',
            ' ',
            {
              type: 'span',
              key: null,
              ref: null,
              props: { className: '!font-[500]', children: 'limited edition' },
              _owner: null,
              _store: {},
            },
            ' offering is the',
            ' ',
            {
              type: 'span',
              key: null,
              ref: null,
              props: { className: '!font-[500]', children: 'best gift' },
              _owner: null,
              _store: {},
            },
            ' for your liberal constituents.',
          ],
        },
        _owner: null,
        _store: {},
      },
      quantity: '2',
    },
  ],
  shipping_address: {
    address_line_1: '',
    address_line_2: '',
    administrative_district_level_1: '',
    country: '',
    first_name: '',
    last_name: '',
    locality: '',
    postal_code: '',
  },
  accept_partial_authorization: False,
  buyer_email_address: '',
  phone: '3134456866',
  order_id: '',
  countryCode: 'US',
  currencyCode: 'USD',
  source_id: 'cnon:CBASEMRzqQGtL9Rw7OzkLcYmZB8oAg',
};
