import { FocusEventHandler, KeyboardEventHandler, MouseEventHandler } from 'react';
import './textarea.css';
export type TextInputProps = {
    value: string;
    name: string;
    onChange?: (value: string) => void;
    required?: boolean;
    pattern?: RegExp;
    min?: number;
    max?: number;
    disabled?: boolean;
    icon?: string;
    onIconClick?: MouseEventHandler;
    className?: string;
    readOnly?: boolean;
    type?: string;
    datatype?: string;
    onKeyUp?: KeyboardEventHandler;
    onBlur?: FocusEventHandler;
    placeholder?: string;
    forwardRef?: any;
};
type TextAreaProps = {
    value: string;
    name: string;
    onChange?: (value: string) => void;
    required?: boolean;
    cols?: number;
    rows?: number;
    disabled?: boolean;
    className?: string;
    readOnly?: boolean;
    datatype?: string;
    onKeyUp?: KeyboardEventHandler;
    onBlur?: FocusEventHandler;
    placeholder?: string;
    forwardRef?: any;
};
export declare const TextAreaInput: ({ name, value, onChange, required, disabled, cols, rows, onKeyUp, onBlur, className, readOnly, datatype, placeholder, forwardRef, }: TextAreaProps) => import("react/jsx-runtime").JSX.Element;
export {};
